"""Build standalone glyph outlines for Library category previews.

Requires Python fontTools and brotli for WOFF2, plus Node for the shared sample
rules. System faces are read from --system-font-dir (Windows Fonts by default).
Missing system faces retain the editor's live-lettering fallback.
"""

import argparse
import json
import os
from pathlib import Path
import subprocess

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "js/generated/font-preview-icons.js"


def system_faces(directory):
	faces = {}
	if not directory.is_dir():
		return faces
	for path in sorted(directory.iterdir()):
		if path.suffix.lower() not in (".ttf", ".otf"):
			continue
		try:
			with TTFont(path, lazy=True) as font:
				for record in font["name"].names:
					if record.nameID in (1, 16):
						faces.setdefault(record.toUnicode().casefold(), path)
		except (OSError, ValueError):
			continue
	return faces


def outline(path, text):
	with TTFont(path) as font:
		glyphs = font.getGlyphSet()
		cmap = font.getBestCmap()
		pen = SVGPathPen(glyphs, ntos=lambda number: format(number, ".3f").rstrip("0").rstrip(".") if number else "0")
		bounds = BoundsPen(glyphs)
		advance = 0
		for char in text:
			if ord(char) not in cmap:
				raise ValueError(f"{path.name} has no glyph for {char!r}")
			glyph = glyphs[cmap[ord(char)]]
			transform = (1, 0, 0, -1, advance, 0)
			glyph.draw(TransformPen(pen, transform))
			glyph.draw(TransformPen(bounds, transform))
			advance += glyph.width
		left, top, right, bottom = bounds.bounds
		padding = max(right - left, bottom - top) * 0.04
		box = [left - padding, top - padding, right - left + padding * 2, bottom - top + padding * 2]
		return {"viewBox": " ".join(format(value, ".3f") for value in box), "path": pen.getCommands()}


def main():
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--system-font-dir", type=Path, default=Path(os.environ.get("WINDIR", "C:/Windows")) / "Fonts")
	parser.add_argument("--check", action="store_true")
	args = parser.parse_args()
	manifest = json.loads((ROOT / "data/fonts.json").read_text(encoding="utf-8"))
	# The editor owns script-aware sample lettering; this generator consumes it.
	program = """
const fs = require('fs'), path = require('path'), vm = require('vm');
const root = process.argv[1];
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'data/fonts.json'), 'utf8'));
const source = fs.readFileSync(path.join(root, 'js/assets/FontBrowserManager.js'), 'utf8');
const samples = vm.runInNewContext(source + '\\nObject.fromEntries(fonts.map(font => [font.id, getFontSampleText(font, "short")]))', { ContentManager: class {}, fonts: manifest.fonts });
process.stdout.write(JSON.stringify(samples));
"""
	samples = json.loads(subprocess.check_output(["node", "-e", program, str(ROOT)], text=True, encoding="utf-8"))
	faces = system_faces(args.system_font_dir)
	icons = {}
	for font in manifest["fonts"]:
		if font.get("system"):
			family = font["family"].split(",")[0].strip().strip('"\'')
			path = faces.get(family.casefold())
			if not path:
				print(f"Skipping unavailable system face: {font['name']}")
				continue
		else:
			path = ROOT / font["file"]
		icons[font["id"]] = outline(path, samples[font["id"]])
	text = "// Generated by python tools/build-font-preview-icons.py; glyph paths, no font fetch.\n"
	text += "const FONT_PREVIEW_ICONS = Object.freeze(" + json.dumps(icons, ensure_ascii=False, indent="\t") + ");\n"
	if args.check:
		if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
			raise SystemExit("Font preview icons are stale")
		print("PASS font preview icons are current")
	else:
		OUTPUT.parent.mkdir(parents=True, exist_ok=True)
		OUTPUT.write_text(text, encoding="utf-8", newline="\n")
		print(f"Generated {len(icons)} font preview icons")


if __name__ == "__main__":
	main()
